# Generated by Django 6.0.5 on 2026-05-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimAirline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(max_length=10, unique=True)),
                ('airline_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DimAirport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10, unique=True)),
                ('airport_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(max_length=5, unique=True)),
                ('reason_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'month', 'day')},
            },
        ),
        migrations.CreateModel(
            name='FactFlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_delay', models.FloatField(blank=True, null=True)),
                ('arrival_delay', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('air_time', models.FloatField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimairline')),
                ('cancellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimcancellation')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimdate')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='warehouse.dimairport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='warehouse.dimairport')),
            ],
        ),
    ]
